[package]
name = "mandelbrot_rust"
version = "0.1.0"
edition = "2024"

# This will instruct Cargo to create a static
# library which CMake can link against
[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0.194"
cxx-qt = { git = "https://github.com/campos02/cxx-qt.git", rev = "56d32708d0643dd07875bff82988ce0ba2bdcbf4" }
cxx-qt-lib = { git = "https://github.com/campos02/cxx-qt.git", rev = "56d32708d0643dd07875bff82988ce0ba2bdcbf4", features = ["qt_gui"] }

[build-dependencies]
# The link_qt_object_files feature is required for statically linking Qt 6.
cxx-qt-build = { version = "0.9.0", features = [ "link_qt_object_files" ] }